### ISSUE TITLE
Startup issue

### ISSUE THREAD

**Issue by sarnobat** [ehoppmann/mlocate-web#1]
I followed the instructions but this is what I ended up with:

```
● gunicorn.service - gunicorn daemon
   Loaded: loaded (/etc/systemd/system/gunicorn.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2018-01-24 21:39:43 PST; 15s ago
 Main PID: 15935 (code=exited, status=203/EXEC)

Jan 24 21:39:43 nuc systemd[1]: Started gunicorn daemon.
Jan 24 21:39:43 nuc systemd[1]: gunicorn.service: Main process exited, code=exited, status=203/EXEC
Jan 24 21:39:43 nuc systemd[1]: gunicorn.service: Unit entered failed state.
Jan 24 21:39:43 nuc systemd[1]: gunicorn.service: Failed with result 'exit-code'.
```

**Comment by ehoppmann** [comment]
I can't reproduce this. There is either a problem with your service file or with your permissions

**Comment by sarnobat** [comment]
Thanks for the quick response. I wish I knew more about virtualenv and gunicorn to debug this myself. I did try chmod 777 -R but that didn't help.

**Comment by ehoppmann** [comment]
My suspicion is that there is an issue with your service definition, possibly the working directory. 

You can try running the webapp directly without registering it as a service by cd-ing to the base directory (containing `app.py`) and then running `./venv/bin/gunicorn --workers 3 -b 0.0.0.0:8000 app:app` - this should give you a server running on port 8000 with 3 worker processes
